server:
  port: 9296

spring:
  application:
    name: MY-CONFIG-SERVER
  cloud:
    config:
      server:
        git:
          uri: https://github.com/riteshrai11786/config-server
          clone-on-start: true